/* generated by unplugin-react-components */
export {}
declare global{
	const ThemeProvider: typeof import('./src/contexts/ThemeContext')['ThemeProvider']
	const SettingsPage: typeof import('./src/pages/settings/index')['default']
}